SELECT
  p.product_id AS product_id ,
  COALESCE(
        ROUND(SUM(p.price * u.units) * 1.0 / SUM(u.units), 2),
        0
    ) AS average_price
FROM prices AS p 
LEFT JOIN 
UnitsSold AS u
ON p.product_id = u.product_id AND u.purchase_date >= p.start_date AND u.purchase_date <= p.end_date
GROUP BY p.product_id
ORDER BY p.product_id;


-- Combination of SUM function and GROUP BY clause plays important role in that solution .
-- COALESCE use to replace the NULL result generated by calculating average value price for products with zero sales (due to the LEFT JOIN), ensuring the output displays 0 instead of NULL.